### ISSUE TITLE
Colons in host variables doesn't work

### ISSUE THREAD

**Issue by Cougar** [appuio/ansible-ini2yaml#4]
I get exception

```python
Traceback (most recent call last):
  File "./ini2yaml", line 58, in <module>
    value = parse_value(hostvar[1])
  File "./ini2yaml", line 28, in parse_value
    result = yaml.load("value: " + value)['value']
  File "/home/cougar/git/ansible-ini2yaml/.env/lib/python2.7/site-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/home/cougar/git/ansible-ini2yaml/.env/lib/python2.7/site-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/home/cougar/git/ansible-ini2yaml/.env/lib/python2.7/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/home/cougar/git/ansible-ini2yaml/.env/lib/python2.7/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/home/cougar/git/ansible-ini2yaml/.env/lib/python2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/home/cougar/git/ansible-ini2yaml/.env/lib/python2.7/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/home/cougar/git/ansible-ini2yaml/.env/lib/python2.7/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/home/cougar/git/ansible-ini2yaml/.env/lib/python2.7/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/home/cougar/git/ansible-ini2yaml/.env/lib/python2.7/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/home/cougar/git/ansible-ini2yaml/.env/lib/python2.7/site-packages/yaml/scanner.py", line 220, in fetch_more_tokens
    return self.fetch_value()
  File "/home/cougar/git/ansible-ini2yaml/.env/lib/python2.7/site-packages/yaml/scanner.py", line 576, in fetch_value
    self.get_mark())
yaml.scanner.ScannerError: mapping values are not allowed here
  in "<string>", line 1, column 17:
    value: 2001:DB8::
                    ^
```

When converting this INI file:

```ini
[nodes]
node1 ipv4=192.0.2.0 ipv6=2001:DB8::
```

**Comment by dtschan** [comment]
Thank you for reporting this issue. I'll look into this. In the meantime you can work around it by applying quotes around the problematic value in the ini inventory, e.g.:

```
[nodes]
node1 ipv4=192.0.2.0 ipv6="2001:DB8::"
```

**Comment by Cougar** [comment]
Sure that I can preprocess the INI file before conversion but I didin't do it because
- the file comes from other system where I can't change the original
- it is quite complicated (and long - over 2000 lines) for simple quoting with `sed` or any other command line tool
- the fix is simple enough and I can use my fork meantime

I did many changes but hopefully the latest is the best and works with any correct INI file (I don't check both start and end quotes).

I'm not sure if there are any other characters that are allowed in INI file but not in YAML…

**Comment by dtschan** [comment]
Ah, I didn't see that you improved the pull request and it passes the test now. Thx. I'll merge and improve upon it. There are indeed other characters that are problematic.
